import { GAME_CONFIG } from "./config.js";
import { isSupabaseConfigured, saveScoreOnline, loadLeaderboard } from "./supabase-client.js";
import { sample, escapeHtml, unescapeHtml, sameAnswer, shuffle } from "./utils.js";
import { sfx, startMusic, initAudio } from "./game/audio.js";
import { sparkle, drawLaser } from "./game/effects.js";
import { getBank } from "./game/questionBank.js";

const app=document.getElementById("app");
let data,scenes;
const state={idx:0,phase:"start",q:0,qs:[],score:0,correct:0,lives:3,streak:0,bossHp:100,muted:false,musicOn:true,vol:2,player:GAME_CONFIG.defaultPlayer,progress:loadProgress()};

function defaultProgress(){return{unlocked:0,stars:Array(8).fill(0),best:Array(8).fill(0),xp:0,coins:0,leaderboard:[]}}
function loadProgress(){try{return JSON.parse(localStorage.getItem(GAME_CONFIG.storageKey))||defaultProgress()}catch{return defaultProgress()}}
function saveProgress(){localStorage.setItem(GAME_CONFIG.storageKey,JSON.stringify(state.progress))}
function isCorrect(pick,q){if(Array.isArray(q.answer))return q.answer.some(a=>sameAnswer(pick,a));return sameAnswer(pick,q.answer)}
function showOptions(q){const map=new Map(),ans=Array.isArray(q.answer)?q.answer:[q.answer];[...ans,...(q.options||[])].forEach(x=>map.set(String(x),String(x)));return shuffle([...map.values()])}
function onlineBadge(){return isSupabaseConfigured?'<span class="px-3 py-1 rounded-full text-sm font-black bg-green-100 text-green-800">Supabase: Connected</span>':'<span class="px-3 py-1 rounded-full text-sm font-black bg-amber-100 text-amber-800">Supabase: Config Needed</span>'}
function shell(c){app.innerHTML=`<header class="text-center text-white mb-6"><div class="inline-flex px-4 py-2 rounded-full bg-white/10 mb-3 font-bold">🔫 Shooting Learning RPG</div><h1 class="text-5xl md:text-7xl font-black">Super Maths Adventure</h1><p class="text-cyan-100">Collecting Data • Online Leaderboard • Supabase</p></header>${c}`}
function badge(t,cls="bg-cyan-100 text-cyan-800"){return`<span class="px-3 py-1 rounded-full text-sm font-black ${cls}">${t}</span>`}
function stars(n){return"⭐".repeat(n)+"☆".repeat(3-n)}
function progressBar(){const pct=Math.round(state.q/(state.qs.length||10)*100);return`<div class="w-full h-3 rounded-full bg-slate-200 overflow-hidden"><div class="h-full bg-gradient-to-r from-cyan-400 to-blue-600" style="width:${pct}%"></div></div>`}
function diagram(){return`<div class="overflow-x-auto my-4"><table class="w-full bg-white rounded-2xl overflow-hidden border"><tr class="bg-blue-50"><th>Category</th><th>Tally</th><th>Frequency</th></tr><tr><td>Apple</td><td>||||/ ||</td><td>7</td></tr><tr><td>Banana</td><td>||||</td><td>4</td></tr><tr><td>Orange</td><td>|||</td><td>3</td></tr></table></div>`}
function speak(text){if(!("speechSynthesis"in window))return;const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.86;speechSynthesis.cancel();speechSynthesis.speak(u)}
function setMusic(mode){startMusic(state.idx,mode,state)}

function renderStart(){setMusic("menu");shell(`<main class="glass rounded-[2rem] p-6 md:p-10 max-w-6xl mx-auto"><div class="grid md:grid-cols-2 gap-8 items-center"><section><div class="text-8xl mb-3">🧙‍♂️🔫</div><h2 class="text-4xl font-black">Super Data Shooting</h2><div class="mt-3">${onlineBadge()}</div><p class="text-slate-600 mt-4 text-lg">แยกโครงสร้างเป็นโปรเจกต์จริง พร้อม Supabase, Online Score และ Leaderboard</p><input id="playerName" class="px-4 py-3 rounded-2xl border font-bold mt-5 w-full" placeholder="Player name" value="${state.player}"/><div class="flex flex-col sm:flex-row gap-3 mt-6"><button id="startBtn" class="btn px-7 py-4 rounded-2xl bg-cyan-500 text-white font-black">Start Story</button><button id="mapBtn" class="btn px-7 py-4 rounded-2xl bg-slate-900 text-white font-black">Scene Map</button></div><div class="flex gap-3 mt-4"><button id="musicBtn" class="btn px-5 py-3 rounded-2xl bg-slate-200 font-black">${state.musicOn?"🎵 Music On":"🔇 Music Off"}</button><button id="muteBtn" class="btn px-5 py-3 rounded-2xl bg-slate-200 font-black">${state.muted?"🔇 Sound Off":"🔊 Sound On"}</button></div></section><section class="dark rounded-[2rem] p-6"><h3 class="text-2xl font-black mb-4">8 Shooting Scenes</h3><div class="grid gap-2 text-sm">${scenes.map((s,i)=>`<div class="p-3 rounded-xl bg-white/10">${i+1}. ${s.topic} ${s.icon}</div>`).join("")}</div></section></div></main>`);document.getElementById("startBtn").onclick=()=>{saveSettings();renderIntro()};document.getElementById("mapBtn").onclick=()=>{saveSettings();renderMap()};document.getElementById("musicBtn").onclick=()=>{state.musicOn=!state.musicOn;renderStart()};document.getElementById("muteBtn").onclick=()=>{state.muted=!state.muted;renderStart()}}
function saveSettings(){initAudio();sfx("click",state.muted,state.vol);state.player=document.getElementById("playerName")?.value.trim()||"Player"}
function renderIntro(){setMusic("learn");shell(`<main class="dark rounded-[2rem] p-8 max-w-4xl mx-auto text-center"><div class="text-8xl mb-4">📊</div><h2 class="text-5xl font-black">Welcome to Data Kingdom!</h2><p class="text-cyan-100 mt-5 text-xl">Use your Data Blaster to collect fair data, organise results, and defeat the Data Dragon.</p><button id="enterBtn" class="btn mt-8 px-8 py-4 rounded-2xl bg-yellow-400 text-slate-900 font-black">Enter Data Kingdom</button></main>`);document.getElementById("enterBtn").onclick=renderMap}
function renderMap(){setMusic("menu");const total=state.progress.stars.reduce((a,b)=>a+b,0);shell(`<main class="glass rounded-[2rem] p-6"><div class="flex flex-col md:flex-row justify-between gap-3 mb-6"><div><h2 class="text-3xl font-black">Scene Map</h2><p class="text-slate-600">Lesson → Worked Examples → Shooting Practice → Shooting Quiz</p></div><div class="flex gap-2 flex-wrap">${onlineBadge()}${badge("Player: "+state.player,"bg-purple-100 text-purple-800")}${badge("Stars: "+total+"/24","bg-yellow-100 text-yellow-800")}${badge("XP: "+state.progress.xp,"bg-green-100 text-green-800")}</div></div><div class="grid md:grid-cols-4 gap-4">${scenes.map((s,i)=>`<div class="${i<=state.progress.unlocked?"":"locked"} rounded-[2rem] p-5 bg-white shadow"><div class="text-4xl">${s.icon}</div><div class="text-sm font-black text-slate-500">${s.title}</div><h3 class="text-xl font-black min-h-[56px]">${s.name}</h3><p class="text-sm text-slate-600">${s.topic}</p><div class="text-2xl mt-2">${stars(state.progress.stars[i]||0)}</div><button class="sceneBtn btn w-full py-3 mt-3 rounded-2xl bg-slate-900 text-white font-black" data-index="${i}">Play</button></div>`).join("")}</div><div class="mt-6 flex gap-3"><button id="homeBtn" class="btn px-5 py-3 rounded-2xl bg-slate-200 font-black">Home</button><button id="leaderBtn" class="btn px-5 py-3 rounded-2xl bg-yellow-100 text-yellow-800 font-black">Leaderboard</button></div></main>`);document.getElementById("homeBtn").onclick=renderStart;document.getElementById("leaderBtn").onclick=renderLeaderboard;document.querySelectorAll(".sceneBtn").forEach(b=>b.onclick=()=>openScene(Number(b.dataset.index)))}
function openScene(i){state.idx=i;state.score=0;state.correct=0;state.lives=3;state.streak=0;state.q=0;state.bossHp=100;renderStory()}
function renderStory(){setMusic("scene");const s=scenes[state.idx];shell(`<main class="glass rounded-[2rem] p-8 max-w-5xl mx-auto"><div class="grid md:grid-cols-[240px_1fr] gap-6 items-center"><section class="text-center rounded-[2rem] bg-cyan-600 p-6 text-white"><div class="text-8xl">${s.icon}</div><h3 class="text-2xl font-black">${s.music}</h3><p>${s.topic}</p></section><section><div class="text-sm font-black text-slate-500">${s.title}</div><h2 class="text-5xl font-black">${s.name}</h2><button id="lessonBtn" class="btn mt-6 px-7 py-4 rounded-2xl bg-cyan-500 text-white font-black">Start Lesson</button></section></div></main>`);document.getElementById("lessonBtn").onclick=()=>renderTeach(0)}
function renderTeach(step){setMusic("learn");const s=scenes[state.idx],text=s.teach[step],last=step>=s.teach.length-1;shell(`<main class="glass rounded-[2rem] p-8 max-w-4xl mx-auto"><h2 class="text-3xl font-black">${s.topic}</h2>${diagram()}<div class="rounded-[2rem] bg-slate-900 text-white p-6"><button id="speakBtn" class="btn float-right px-4 py-3 rounded-2xl bg-white/10">🔊</button><p class="text-3xl font-black">${text}</p></div><div class="mt-6 flex justify-between gap-3"><button id="backBtn" class="btn px-5 py-3 rounded-2xl bg-slate-200 font-black">Back</button><button id="nextBtn" class="btn px-7 py-3 rounded-2xl bg-cyan-500 text-white font-black">${last?"Worked Examples":"Next"}</button></div></main>`);document.getElementById("speakBtn").onclick=()=>speak(text);document.getElementById("backBtn").onclick=()=>step>0?renderTeach(step-1):renderStory();document.getElementById("nextBtn").onclick=()=>last?renderWorked():renderTeach(step+1)}
function renderWorked(){setMusic("learn");const s=scenes[state.idx];shell(`<main class="glass rounded-[2rem] p-8 max-w-5xl mx-auto"><h2 class="text-4xl font-black mb-2">📝 Worked Examples</h2><p class="text-slate-600 mb-5">อ่านเฉลยวิธีคิดก่อนเข้าเกมยิงเป้า</p><div class="grid gap-4">${s.worked.map((w,i)=>`<div class="p-5 rounded-3xl bg-white border shadow"><div class="font-black text-xl">Example ${i+1}: ${w[0]}</div><div class="mt-3 p-4 rounded-2xl bg-green-50 text-green-900 font-bold">Answer & Thinking: ${w[1]}</div></div>`).join("")}</div><button id="practiceBtn" class="btn mt-6 px-7 py-3 rounded-2xl bg-cyan-500 text-white font-black">Start Shooting Practice</button></main>`);document.getElementById("practiceBtn").onclick=startPractice}
function startPractice(){setMusic("shoot");state.phase="practice";state.q=0;state.qs=sample(getBank(scenes[state.idx].id),3);renderQuestion()}
function startQuiz(){setMusic("shoot");state.phase="quiz";state.q=0;state.correct=0;state.lives=3;state.streak=0;state.bossHp=100;state.qs=sample(getBank(scenes[state.idx].id),state.idx===7?15:10);renderQuestion()}
function thaiHelpText(q){return`<div class="p-4 rounded-2xl bg-amber-50 text-amber-900 font-bold border">🇹🇭 ${q.thai||"แปลโจทย์นี้เป็นภาษาไทยเพื่อช่วยอ่านโจทย์ แต่ไม่มีเฉลยคำตอบ"}<div class="mt-2 text-sm">คำแปลนี้ไม่มีเฉลยคำตอบ</div></div>`}
function renderBossBar(){return state.idx===7&&state.phase==="quiz"?`<div class="my-3"><div class="font-black text-rose-700 mb-1">🐉 Boss HP: ${Math.max(0,state.bossHp)}%</div><div class="bossbar"><div class="bossfill" style="width:${Math.max(0,state.bossHp)}%"></div></div></div>`:""}
function renderQuestion(feedback=""){const s=scenes[state.idx],q=state.qs[state.q];shell(`<main class="glass rounded-[2rem] p-6 max-w-5xl mx-auto"><section class="flex flex-col md:flex-row justify-between gap-3"><div><div class="text-sm font-black text-slate-500">${state.phase.toUpperCase()} • SHOOTING MODE</div><h2 class="text-3xl font-black">${s.topic}</h2></div><div class="flex gap-2 flex-wrap">${badge("Q "+(state.q+1)+"/"+state.qs.length)}${badge("❤️ "+state.lives,"bg-rose-100 text-rose-800")}${badge("Score "+state.score,"bg-yellow-100 text-yellow-800")}${badge("Combo "+state.streak,"bg-purple-100 text-purple-800")}</div></section>${renderBossBar()}<div class="my-5">${progressBar()}</div><section id="questionBox" class="rounded-[2rem] bg-white border p-5 shadow"><button id="speakQBtn" class="btn float-right px-4 py-3 rounded-2xl bg-blue-100">🔊</button><h3 class="text-2xl md:text-3xl font-black">${q.text}</h3><div class="grid gap-3 mt-5">${showOptions(q).map((op,i)=>`<button id="target${i}" class="shootBtn target btn p-4 rounded-2xl text-xl md:text-2xl font-black" data-answer="${escapeHtml(op)}"><span class="enemy">${s.enemy}</span>${op}</button>`).join("")}</div><div class="text-5xl mt-5">🔫</div></section><section id="feedback" class="mt-4">${feedback}</section><div class="mt-5 flex gap-3"><button id="mapBtn2" class="btn px-5 py-3 rounded-2xl bg-slate-200 font-black">Map</button><button id="hintBtn" class="btn px-5 py-3 rounded-2xl bg-blue-100 text-blue-800 font-black">Hint</button><button id="thaiBtn" class="btn px-5 py-3 rounded-2xl bg-amber-100 text-amber-800 font-black">TH แปลโจทย์</button></div></main>`);document.getElementById("speakQBtn").onclick=()=>speak(q.text);document.getElementById("mapBtn2").onclick=renderMap;document.getElementById("hintBtn").onclick=()=>document.getElementById("feedback").innerHTML=`<div class="p-4 rounded-2xl bg-blue-100 text-blue-900 font-bold">💡 ${s.teach[0]}</div>`;document.getElementById("thaiBtn").onclick=()=>document.getElementById("feedback").innerHTML=thaiHelpText(q);document.querySelectorAll(".shootBtn").forEach(btn=>btn.onclick=()=>shoot(unescapeHtml(btn.dataset.answer),btn.id))}
function shoot(choice,targetId){drawLaser(targetId);sfx("laser",state.muted,state.vol);setTimeout(()=>isCorrect(choice,state.qs[state.q])?correct():wrong(),170)}
function correct(){state.correct++;state.streak++;state.score+=10+(state.streak>=3?5:0);if(state.idx===7&&state.phase==="quiz")state.bossHp-=Math.ceil(100/state.qs.length);sfx("correct",state.muted,state.vol);sparkle(true);nextQuestion(`<div class="p-4 rounded-2xl bg-green-100 text-green-900 font-black">✅ Correct Shot!</div>`,true)}
function wrong(){state.lives--;state.streak=0;sfx("wrong",state.muted,state.vol);sparkle(false);const box=document.getElementById("questionBox");if(box)box.classList.add("shake");if(state.lives<=0){setTimeout(gameOver,500);return}nextQuestion(`<div class="p-4 rounded-2xl bg-rose-100 text-rose-900 font-black">❌ Missed target.</div>`,false)}
function nextQuestion(message,ok){document.getElementById("feedback").innerHTML=message;setTimeout(()=>{state.q++;if(state.q>=state.qs.length){if(state.phase==="practice")return practiceClear();return complete()}renderQuestion()},ok?750:1100)}
function practiceClear(){shell(`<main class="glass rounded-[2rem] p-8 max-w-xl mx-auto text-center"><div class="text-7xl">🏅</div><h2 class="text-4xl font-black">Practice Clear!</h2><p class="text-slate-600">Bonus +50</p><button id="quizBtn" class="btn mt-7 px-8 py-4 rounded-2xl bg-cyan-500 text-white font-black">Start Shooting Quiz</button></main>`);document.getElementById("quizBtn").onclick=()=>{state.score+=50;startQuiz()}}
function gameOver(){shell(`<main class="glass rounded-[2rem] p-8 max-w-xl mx-auto text-center"><div class="text-7xl">💥</div><h2 class="text-4xl font-black">Try Again</h2><button id="reviewBtn" class="btn py-4 px-8 rounded-2xl bg-blue-100 text-blue-800 font-black">Review Worked Examples</button></main>`);document.getElementById("reviewBtn").onclick=renderWorked}
async function complete(){const total=state.qs.length,star=state.correct/total>=.9?3:state.correct/total>=.75?2:state.correct/total>=.6?1:0,passed=star>0,s=scenes[state.idx];state.progress.stars[state.idx]=Math.max(state.progress.stars[state.idx],star);state.progress.best[state.idx]=Math.max(state.progress.best[state.idx]||0,state.score);state.progress.xp+=state.score;state.progress.coins+=star*25;if(passed)state.progress.unlocked=Math.max(state.progress.unlocked,Math.min(state.idx+1,scenes.length-1));state.progress.leaderboard.push({name:state.player,scene:s.topic,score:state.score});state.progress.leaderboard=state.progress.leaderboard.sort((a,b)=>b.score-a.score).slice(0,20);saveProgress();const onlineResult=await saveScoreOnline({gameSlug:GAME_CONFIG.currentGameSlug,sceneNo:state.idx+1,playerName:state.player,score:state.score,correct:state.correct,total,stars:star,xp:state.score,coins:star*25});sfx("coin",state.muted,state.vol);shell(`<main class="glass rounded-[2rem] p-8 max-w-2xl mx-auto text-center"><div class="text-8xl">${passed?"🏆":"📚"}</div><h2 class="text-5xl font-black">${passed?"Scene Complete!":"Keep Practicing!"}</h2><p>${s.name}</p><div class="my-4">${onlineResult.ok?'<span class="px-4 py-2 rounded-full bg-green-100 text-green-800 font-black">✅ Saved to Supabase</span>':'<span class="px-4 py-2 rounded-full bg-amber-100 text-amber-800 font-black">⚠️ Local saved only</span>'}</div><div class="text-5xl my-5">${stars(star)}</div><div class="grid grid-cols-2 gap-3 my-5"><div class="p-4 rounded-2xl bg-green-50"><b>Correct</b><br>${state.correct}/${total}</div><div class="p-4 rounded-2xl bg-yellow-50"><b>Score</b><br>${state.score}</div></div><button id="backMapBtn" class="btn py-4 px-8 rounded-2xl bg-cyan-500 text-white font-black">Scene Map</button><button id="onlineLeaderBtn" class="btn mt-3 py-4 px-8 rounded-2xl bg-yellow-100 text-yellow-800 font-black">Online Leaderboard</button></main>`);document.getElementById("backMapBtn").onclick=renderMap;document.getElementById("onlineLeaderBtn").onclick=renderLeaderboard}
async function renderLeaderboard(){const onlineRows=await loadLeaderboard(20),rows=onlineRows.length?onlineRows:state.progress.leaderboard;shell(`<main class="glass rounded-[2rem] p-6 max-w-4xl mx-auto"><h2 class="text-4xl font-black">🏆 ${onlineRows.length?"Online":"Local"} Leaderboard</h2><div class="mt-2">${onlineBadge()}</div><div class="mt-5 grid gap-2">${rows.length?rows.map((r,i)=>`<div class="p-4 rounded-2xl bg-slate-50 flex flex-col md:flex-row md:justify-between gap-2"><b>#${i+1} ${r.player_name||r.name||"Player"}</b><span>${r.scene_name||r.scene||""}</span><b>${r.score}</b></div>`).join(""):'<div class="p-4 rounded-2xl bg-slate-50">No scores yet.</div>'}</div><button id="leaderBackBtn" class="btn mt-6 px-6 py-3 rounded-2xl bg-cyan-500 text-white font-black">Back</button></main>`);document.getElementById("leaderBackBtn").onclick=renderMap}
async function boot(){const res=await fetch("./data/collecting_data.json");data=await res.json();scenes=data.scenes;renderStart()}
boot();
