let ctx=null,enabled=localStorage.getItem('sma_audio')!=='off',bgm=null;
function ac(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();return ctx}
function tone(f=440,d=.1,type='sine',v=.05,delay=0){if(!enabled)return;const c=ac(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(f,c.currentTime+delay);g.gain.setValueAtTime(.0001,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(v,c.currentTime+delay+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(g);g.connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}
function noise(d=.18,v=.06){if(!enabled)return;const c=ac(),b=c.createBuffer(1,c.sampleRate*d,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,2);const s=c.createBufferSource(),g=c.createGain();g.gain.value=v;s.buffer=b;s.connect(g);g.connect(c.destination);s.start()}
export function unlockAudio(){if(enabled)ac().resume()}
export function isAudioOn(){return enabled}
export function toggleAudio(){enabled=!enabled;localStorage.setItem('sma_audio',enabled?'on':'off');if(!enabled)stopBgm();return enabled}
export function sfx(n){if(!enabled)return;if(n==='click')tone(520,.07,'square',.035);else if(n==='laser'){tone(880,.08,'sawtooth',.06);tone(1320,.06,'square',.035,.04)}else if(n==='correct'){tone(660,.08,'sine',.06);tone(880,.1,'sine',.07,.08);tone(1100,.12,'sine',.06,.16)}else if(n==='wrong'){tone(220,.13,'sawtooth',.07);tone(160,.18,'sawtooth',.05,.12)}else if(n==='coin'){tone(900,.07,'triangle',.06);tone(1200,.1,'triangle',.06,.08)}else if(n==='bossHit'){noise(.15,.06);tone(160,.12,'sawtooth',.07)}else if(n==='victory'){[523,659,784,1046].forEach((f,i)=>tone(f,.18,'triangle',.07,i*.12))}else if(n==='unlock'){[600,900,1200].forEach((f,i)=>tone(f,.16,'triangle',.06,i*.1))}}
export function playBgm(world=1){if(!enabled)return;stopBgm();let base=[196,220,246,261,293,329,349,392][(world-1)%8],step=0;bgm=setInterval(()=>{if(!enabled)return;let scale=[0,3,5,7,10,7,5,3];tone(base*Math.pow(2,scale[step%8]/12),.22,'sine',.028);if(step%4===0)tone(base/2,.35,'triangle',.018);step++},290)}
export function stopBgm(){if(bgm){clearInterval(bgm);bgm=null}}
