import{r,shuffle,opts}from'./utils.js';function q(text,options,answer,thai=''){return{text,options:opts(options,answer),answer,thai}}function fill(base,extra=['correct','wrong A','wrong B','wrong C']){let b=[...base];while(b.length<50){let x=extra[r(0,extra.length-1)];b.push(q(`Choose: ${x}`,[x,...shuffle(extra).slice(0,3)],x,'เลือกคำตอบที่ถูกต้อง'))}return b}
export function getBank(slug,id,topic){if(slug==='super-integers')return integers();if(slug==='super-decimals-shooting-v2')return decimals();if(slug==='super-place-value')return place();if(slug==='super-algebra')return algebra();if(slug==='super-geometry')return geometry();if(slug==='super-fractions')return fractions();if(slug==='super-percentages')return percentages();return dataBank(id)}
function dataBank(id){if(id==='tally'){let b=[];for(let i=0;i<50;i++){let a=r(1,20),g=Math.floor(a/5),m=a%5,t='||||/ '.repeat(g)+'|'.repeat(m);b.push(q(`Tally marks "${t.trim()}" show what frequency?`,[a,a+1,Math.max(0,a-1),a+5],a,'อ่าน tally marks'))}return b}return fill([q('Which is data?',['survey results','empty page','random guess','decoration'],'survey results','ข้อใดเป็นข้อมูล'),q('Favourite colour is what type of data?',['categorical data','numerical data','continuous data','decimal data'],'categorical data','สีที่ชอบเป็นข้อมูลชนิดใด')],['categorical data','numerical data','biased','sample','population'])}
function integers(){let b=[];for(let i=0;i<50;i++){let a=r(-20,20),c=r(-20,20),op=['+','-','×'][r(0,2)],ans=op==='+'?a+c:op==='-'?a-c:a*c;b.push(q(`${a} ${op} ${c} = ?`,[ans,ans+1,ans-1,-ans],ans,'คำนวณจำนวนเต็ม'))}return b}
function decimals(){let b=[];for(let i=0;i<50;i++){let a=(r(1,99)/10).toFixed(1),c=(r(1,99)/10).toFixed(1),ans=(Number(a)+Number(c)).toFixed(1);b.push(q(`${a} + ${c} = ?`,[ans,(Number(ans)+0.1).toFixed(1),(Number(ans)-0.1).toFixed(1),String(Number(ans))],ans,'บวกทศนิยม'))}return b}
function place(){let b=[];for(let i=0;i<50;i++){let n=r(1000,99999),digit=String(n)[0];b.push(q(`What is the first digit in ${n}?`,[digit,String(+digit+1),String(+digit-1),'0'],digit,'ถามหลักของตัวเลข'))}return b}
function algebra(){let b=[];for(let i=0;i<50;i++){let x=r(1,12),a=r(2,9),c=r(1,20),ans=a*x+c;b.push(q(`If x=${x}, what is ${a}x + ${c}?`,[ans,ans+1,ans-1,a+c],ans,'แทนค่าในนิพจน์'))}return b}
function geometry(){let b=[];for(let i=0;i<50;i++){let a=r(20,160),ans=180-a;b.push(q(`Angles on a straight line: ${a}° + x = 180°. x = ?`,[ans,ans+10,Math.abs(ans-10),180],ans,'มุมบนเส้นตรงรวม 180 องศา'))}return b}
function fractions(){let b=[];for(let i=0;i<50;i++){let d=[2,3,4,5,6,8,10][r(0,6)],n=r(1,d-1);b.push(q(`What is ${n}/${d} of ${d*10}?`,[n*10,n*10+1,n*5,d*10],n*10,'หาเศษส่วนของจำนวน'))}return b}
function percentages(){let b=[];for(let i=0;i<50;i++){let p=[10,20,25,50][r(0,3)],n=[40,60,80,100,200][r(0,4)],ans=n*p/100;b.push(q(`${p}% of ${n} = ?`,[ans,ans+5,ans-5,n],ans,'หาร้อยละของจำนวน'))}return b}