import { rand, shuffle, uniqueOptions } from "../utils.js";
function choice(text, options, answer, thai=""){return {text,options:uniqueOptions(options,answer),answer,thai}}
function fill(base,extra=["categorical data","numerical data","discrete data","continuous data","biased","fair","sample","population"]){const b=[...base];while(b.length<50){const x=extra[rand(0,extra.length-1)];b.push(choice(`Shoot the correct word: ${x}`,[x,...shuffle(extra).slice(0,3)],x,"เลือกคำศัพท์ที่ถูกต้อง"))}return b.slice(0,50)}
export function bankCollect(){return fill([choice("Which is data?",["survey results","empty page","random guess","decoration"],"survey results","ข้อใดเป็นข้อมูล"),choice("Which question is fair?",["What is your favourite fruit?","Do you love amazing apples?","Why is football the best?","You like maths, right?"],"What is your favourite fruit?","เลือกคำถามที่เป็นกลาง"),choice("A biased question is usually...",["unfair","neutral","random sample","frequency"],"unfair","คำถามลำเอียงเป็นอย่างไร"),choice("Why do we collect data?",["to answer a question","to decorate a page","to avoid counting","to hide results"],"to answer a question","เก็บข้อมูลเพื่ออะไร")],["survey results","fair","unfair","biased","data","question","answer","collecting data"])}
export function bankTypes(){return fill([choice("Favourite colour is what type of data?",["categorical data","numerical data","continuous data","decimal data"],"categorical data","สีที่ชอบเป็นข้อมูลชนิดใด"),choice("Number of pets is what type of data?",["discrete data","continuous data","categorical data","biased data"],"discrete data","จำนวนสัตว์เลี้ยงเป็นข้อมูลชนิดใด"),choice("Height is what type of data?",["continuous data","discrete data","categorical data","tally data"],"continuous data","ส่วนสูงเป็นข้อมูลชนิดใด"),choice("Shoe size is usually...",["numerical data","categorical data","biased question","sample"],"numerical data","ขนาดรองเท้าเป็นข้อมูลชนิดใด")])}
export function bankQuestionnaire(){return fill([choice("A question with fixed choices is called...",["closed question","open question","biased question","frequency"],"closed question","คำถามที่มีตัวเลือกตายตัว"),choice("A question allowing a long answer is called...",["open question","closed question","tally","sample"],"open question","คำถามที่ตอบยาวได้"),choice("A good questionnaire question should be...",["clear and neutral","leading and biased","long and confusing","only for friends"],"clear and neutral","คำถามที่ดีควรเป็นอย่างไร"),choice("“Why do you like this subject?” is...",["open question","closed question","frequency table","biased sample"],"open question","คำถามนี้เป็นแบบใด")],["closed question","open question","clear and neutral","biased","questionnaire","fixed choices","long answer","neutral"])}
export function bankTally(){const b=[];for(let i=0;i<50;i++){const a=rand(1,20),groups=Math.floor(a/5),rem=a%5,tally="||||/ ".repeat(groups)+"|".repeat(rem);b.push(choice(`Tally marks "${tally.trim()}" show what frequency?`,[a,a+1,Math.max(0,a-1),a+5],a,"อ่าน tally marks"))}return b}
export function bankFrequency(){const b=[];for(let i=0;i<50;i++){const a=rand(1,20),c=rand(1,20),d=rand(1,20),sum=a+c+d;b.push(choice(`A frequency table has ${a}, ${c}, and ${d}. What is total frequency?`,[sum,sum+1,sum-1,a+c],sum,"หาความถี่รวม"));const total=sum+rand(1,10),missing=total-a-c;b.push(choice(`Total frequency is ${total}. Known frequencies are ${a} and ${c}. Missing frequency?`,[missing,missing+1,Math.max(0,missing-1),total-a],missing,"หาความถี่ที่หายไป"))}return b.slice(0,50)}
export function bankSampling(){return fill([choice("The whole group being studied is called what?",["population","sample","frequency","tally"],"population","กลุ่มทั้งหมดเรียกว่าอะไร"),choice("A smaller group chosen from the population is called what?",["sample","population","table","survey"],"sample","กลุ่มย่อยที่เลือกมาเรียกว่าอะไร"),choice("Surveying only football players about favourite sport is likely to be...",["biased","fair","continuous","decimal"],"biased","ตัวอย่างนี้ลำเอียงหรือไม่"),choice("A good sample should be...",["representative","biased","only friends","too small"],"representative","กลุ่มตัวอย่างที่ดีควรเป็นอย่างไร")],["population","sample","representative","biased","random sample","whole group","smaller group","fair"])}
export function bankOrganise(){const b=[];for(let i=0;i<50;i++){const arr=["A","B","A","C","A","B","D","A"].slice(0,rand(5,8)),countA=arr.filter(x=>x==="A").length;b.push(choice(`Raw data: ${arr.join(", ")}. What is the frequency of A?`,[countA,countA+1,Math.max(0,countA-1),arr.length],countA,"หาความถี่ของ A"));const nums=[rand(10,99),rand(10,99),rand(10,99),rand(10,99)],max=Math.max(...nums);b.push(choice(`Shoot the greatest number: ${nums.map(x=>x.toLocaleString()).join(", ")}`,nums.map(x=>x.toLocaleString()),max.toLocaleString(),"ยิงจำนวนที่มากที่สุด"))}return b.slice(0,50)}
export function bankBoss(){const b=[...bankCollect().slice(0,6),...bankTypes().slice(0,6),...bankQuestionnaire().slice(0,6),...bankTally().slice(0,8),...bankFrequency().slice(0,8),...bankSampling().slice(0,6),...bankOrganise().slice(0,6)];b.push(choice("Which is greater: 1,250 or 985?",["1,250","985","equal","1.250"],"1,250","เปรียบเทียบจำนวนที่มี comma"));b.push(choice("Which is greater: 2.50 or 2.5?",["equal","2.50","2.5","greater"],"equal","เปรียบเทียบทศนิยม"));b.push(choice("Which is greater: 0.80 or 0.8?",["equal","0.80","0.8","greater"],"equal","เปรียบเทียบทศนิยม"));b.push(choice("Shoot the greatest value: 0.8, 0.75, 0.09, 0.80",["0.8","0.75","0.09","0.80"],["0.8","0.80"],"ยิงค่าที่มากที่สุด เกมรับค่าที่เท่ากัน"));return shuffle(b).slice(0,50)}
export function getBank(sceneId){if(sceneId==="collect")return bankCollect();if(sceneId==="types")return bankTypes();if(sceneId==="questionnaire")return bankQuestionnaire();if(sceneId==="tally")return bankTally();if(sceneId==="frequency")return bankFrequency();if(sceneId==="sampling")return bankSampling();if(sceneId==="organise")return bankOrganise();return bankBoss()}
